package com.inglessobmedida.youngenglish;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.provider.Settings;import android.webkit.*;import android.widget.Toast;import java.util.*;

public class MainActivity extends Activity {
 private static final String HOME="https://youngenglish-equipesonar-1862.vercel.app/"; private WebView web; private ValueCallback<Uri[]> fileCb; private static final int FILE_REQ=42;
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);CookieManager.getInstance().setAcceptCookie(true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("youngenglish-equipesonar-1862.vercel.app".equals(u.getHost()))return false;startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}});web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest r){runOnUiThread(()->{List<String> ok=new ArrayList<>();for(String x:r.getResources())if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(x))ok.add(x);if(ok.isEmpty())r.deny();else if(Build.VERSION.SDK_INT<23||checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)r.grant(ok.toArray(new String[0]));else{requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},7);r.deny();}});}@Override public boolean onShowFileChooser(WebView w,ValueCallback<Uri[]> cb,FileChooserParams p){fileCb=cb;startActivityForResult(p.createIntent(),FILE_REQ);return true;}});web.loadUrl(HOME);}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==FILE_REQ&&fileCb!=null){fileCb.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));fileCb=null;}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)Toast.makeText(this,"Microfone liberado. Tente gravar novamente.",Toast.LENGTH_SHORT).show();}
}
